# Generated by Django 3.2.3 on 2021-05-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser', models.CharField(max_length=20)),
                ('version', models.CharField(max_length=50)),
                ('apg_url', models.TextField()),
                ('test_url', models.TextField()),
                ('inc_method', models.TextField()),
                ('global_properties', models.TextField(null=True)),
                ('object_properties', models.TextField(null=True)),
                ('event_set', models.TextField(null=True)),
                ('event_list', models.TextField(null=True)),
                ('timed_out', models.BooleanField(default=False)),
                ('auth_failed', models.BooleanField(default=False)),
                ('url_dict_version', models.TextField(default='Unknown')),
                ('loading_time', models.IntegerField(null=True)),
                ('headless', models.BooleanField(default=False)),
                ('gp_window_onerror', models.TextField(null=True)),
                ('gp_window_onblur', models.TextField(null=True)),
                ('gp_window_postMessage', models.TextField(null=True)),
                ('gp_window_getComputedStyle', models.TextField(null=True)),
                ('gp_window_hasOwnProperty', models.TextField(null=True)),
                ('gp_download_bar_height', models.TextField(null=True)),
                ('gp_securitypolicyviolation', models.TextField(null=True)),
                ('op_frame_count', models.TextField(null=True)),
                ('op_win_window', models.TextField(null=True)),
                ('op_win_CSS2Properties', models.TextField(null=True)),
                ('op_win_origin', models.TextField(null=True)),
                ('op_win_opener', models.TextField(null=True)),
                ('op_el_height', models.TextField(null=True)),
                ('op_el_width', models.TextField(null=True)),
                ('op_el_naturalHeight', models.TextField(null=True)),
                ('op_el_naturalWidth', models.TextField(null=True)),
                ('op_el_videoWidth', models.TextField(null=True)),
                ('op_el_videoHeight', models.TextField(null=True)),
                ('op_el_duration', models.TextField(null=True)),
                ('op_el_networkState', models.TextField(null=True)),
                ('op_el_readyState', models.TextField(null=True)),
                ('op_el_buffered', models.TextField(null=True)),
                ('op_el_paused', models.TextField(null=True)),
                ('op_el_seekable', models.TextField(null=True)),
                ('op_el_sheet', models.TextField(null=True)),
                ('op_el_media_error', models.TextField(null=True)),
            ],
        ),
    ]
