# Generated by Django 3.2.3 on 2021-05-28 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbcon', '0002_auto_20210528_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='WindowProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_frame_count', models.TextField()),
                ('op_win_window', models.TextField()),
                ('op_win_CSS2Properties', models.TextField()),
                ('op_win_origin', models.TextField()),
                ('op_win_opener', models.TextField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='objectproperties',
            name='op',
        ),
        migrations.RemoveField(
            model_name='objectproperties',
            name='op_frame_count',
        ),
        migrations.RemoveField(
            model_name='objectproperties',
            name='op_win_CSS2Properties',
        ),
        migrations.RemoveField(
            model_name='objectproperties',
            name='op_win_opener',
        ),
        migrations.RemoveField(
            model_name='objectproperties',
            name='op_win_origin',
        ),
        migrations.RemoveField(
            model_name='objectproperties',
            name='op_win_window',
        ),
        migrations.AlterField(
            model_name='events',
            name='event_list',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_set',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='globalproperties',
            name='gp_download_bar_height',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='globalproperties',
            name='gp_securitypolicyviolation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='globalproperties',
            name='gp_window_getComputedStyle',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='globalproperties',
            name='gp_window_hasOwnProperty',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='globalproperties',
            name='gp_window_onblur',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='globalproperties',
            name='gp_window_onerror',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='globalproperties',
            name='gp_window_postMessage',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='objectproperties',
            name='op_el_buffered',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='objectproperties',
            name='op_el_duration',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='objectproperties',
            name='op_el_height',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='objectproperties',
            name='op_el_media_error',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='objectproperties',
            name='op_el_naturalHeight',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='objectproperties',
            name='op_el_naturalWidth',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='objectproperties',
            name='op_el_networkState',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='objectproperties',
            name='op_el_paused',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='objectproperties',
            name='op_el_readyState',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='objectproperties',
            name='op_el_seekable',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='objectproperties',
            name='op_el_sheet',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='objectproperties',
            name='op_el_videoHeight',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='objectproperties',
            name='op_el_videoWidth',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='objectproperties',
            name='op_el_width',
            field=models.TextField(),
        ),
        migrations.AddConstraint(
            model_name='objectproperties',
            constraint=models.UniqueConstraint(fields=('op_el_height', 'op_el_width', 'op_el_naturalHeight', 'op_el_naturalWidth', 'op_el_videoHeight', 'op_el_videoWidth', 'op_el_duration', 'op_el_networkState', 'op_el_readyState', 'op_el_buffered', 'op_el_paused', 'op_el_seekable', 'op_el_sheet', 'op_el_media_error'), name='op'),
        ),
        migrations.AddConstraint(
            model_name='windowproperties',
            constraint=models.UniqueConstraint(fields=('op_frame_count', 'op_win_window', 'op_win_CSS2Properties', 'op_win_origin', 'op_win_opener'), name='win'),
        ),
        migrations.AddField(
            model_name='observation',
            name='window_properties',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbcon.windowproperties'),
        ),
    ]
