# Generated by Django 3.2.3 on 2021-06-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbcon', '0003_auto_20210528_1824'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='objectproperties',
            name='op',
        ),
        migrations.RemoveConstraint(
            model_name='windowproperties',
            name='win',
        ),
        migrations.AddField(
            model_name='objectproperties',
            name='op_el_contentDocument',
            field=models.TextField(default='js-null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='windowproperties',
            name='op_win_history_length',
            field=models.TextField(default='0'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='objectproperties',
            constraint=models.UniqueConstraint(fields=('op_el_height', 'op_el_width', 'op_el_naturalHeight', 'op_el_naturalWidth', 'op_el_videoHeight', 'op_el_videoWidth', 'op_el_duration', 'op_el_networkState', 'op_el_readyState', 'op_el_buffered', 'op_el_paused', 'op_el_seekable', 'op_el_sheet', 'op_el_media_error', 'op_el_contentDocument'), name='op'),
        ),
        migrations.AddConstraint(
            model_name='windowproperties',
            constraint=models.UniqueConstraint(fields=('op_frame_count', 'op_win_window', 'op_win_CSS2Properties', 'op_win_origin', 'op_win_opener', 'op_win_history_length'), name='win'),
        ),
    ]
