# Generated by Django 3.2.3 on 2021-07-26 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbcon', '0006_observation_retest'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeakResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loading_time', models.IntegerField(null=True)),
                ('timed_out', models.BooleanField(default=False)),
                ('apg_url', models.TextField(null=True)),
                ('complete_time', models.IntegerField(null=True)),
                ('retest_num', models.IntegerField(default=False)),
                ('cookies', models.BooleanField(default=False)),
                ('site', models.TextField()),
                ('browser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbcon.browser')),
                ('events', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbcon.events')),
                ('global_properties', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbcon.globalproperties')),
                ('object_properties', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbcon.objectproperties')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbcon.test')),
                ('window_properties', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbcon.windowproperties')),
            ],
        ),
    ]
