# Generated by Django 3.2.3 on 2021-09-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbcon', '0007_leakresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='load_count',
            field=models.IntegerField(default=0),
        ),
    ]
