# Generated by Django 3.2.3 on 2021-09-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbcon', '0008_events_load_count'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='events',
            name='events',
        ),
        migrations.AddConstraint(
            model_name='events',
            constraint=models.UniqueConstraint(fields=('event_set', 'event_list', 'load_count'), name='events'),
        ),
    ]
