# Generated by Django 3.2.3 on 2021-09-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbcon', '0009_auto_20210910_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieSecFetch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser', models.TextField()),
                ('version', models.TextField()),
                ('inc_method', models.TextField()),
                ('org_site', models.TextField()),
                ('rec_site', models.TextField()),
                ('c_ns_f', models.TextField()),
                ('c_ns_t', models.TextField()),
                ('c_n_f', models.TextField()),
                ('c_n_t', models.TextField()),
                ('c_l_f', models.TextField()),
                ('c_l_t', models.TextField()),
                ('c_s_f', models.TextField()),
                ('c_s_t', models.TextField()),
                ('sec_fetch_dest', models.TextField()),
                ('sec_fetch_mode', models.TextField()),
                ('sec_fetch_site', models.TextField()),
                ('sec_fetch_user', models.TextField()),
            ],
        ),
    ]
