# Generated by Django 3.2.4 on 2021-06-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_id', models.IntegerField(db_column='url_id')),
                ('url_dict_version', models.TextField(db_column='url_dict_version')),
                ('ecohd_status', models.IntegerField(db_column='Status-Code')),
                ('body', models.TextField(db_column='body', default='empty')),
                ('xcto', models.TextField(db_column='X-Content-Type-Options', default='empty')),
                ('xfo', models.TextField(db_column='X-Frame-Options', default='empty')),
                ('ct', models.TextField(db_column='Content-Type', default='empty')),
                ('cd', models.TextField(db_column='Content-Disposition', default='empty')),
                ('corp', models.TextField(db_column='Cross-Origin-Resource-Policy', default='empty')),
                ('coop', models.TextField(db_column='Cross-Origin-Opener-Policy', default='empty')),
                ('loc', models.TextField(db_column='Location', default='empty')),
            ],
        ),
        migrations.AddConstraint(
            model_name='urldict',
            constraint=models.UniqueConstraint(fields=('url_id', 'url_dict_version'), name='unique_url_for_version'),
        ),
    ]
