# Generated by Django 3.2.5 on 2021-07-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_url', models.TextField()),
                ('req_method', models.TextField()),
                ('req_headers', models.TextField()),
                ('req_body_hash', models.TextField()),
                ('req_body_info', models.TextField()),
                ('resp_version', models.TextField()),
                ('resp_code', models.IntegerField()),
                ('resp_headers', models.TextField()),
                ('resp_body_hash', models.TextField()),
                ('resp_body_info', models.TextField()),
                ('cookies', models.BooleanField()),
                ('site', models.TextField()),
                ('hash_uniq', models.TextField(unique=True)),
                ('count', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddIndex(
            model_name='url_data',
            index=models.Index(fields=['hash_uniq'], name='db_url_data_hash_un_2ade74_idx'),
        ),
        migrations.AddIndex(
            model_name='url_data',
            index=models.Index(fields=['site', 'req_url'], name='db_url_data_site_652ec7_idx'),
        ),
    ]
