# Generated by Django 3.2.5 on 2021-07-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url_data',
            name='real_site',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
    ]
