# Generated by Django 3.2.5 on 2021-07-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_url_data_resp_body_tika_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_data',
            name='req_headers',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='url_data',
            name='resp_body_tika_info',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='url_data',
            name='resp_headers',
            field=models.JSONField(),
        ),
    ]
