# Generated by Django 3.2.5 on 2021-09-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_site_results_confirmed_df_dict'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='url_data',
            name='db_url_data_site_652ec7_idx',
        ),
        migrations.AddIndex(
            model_name='url_data',
            index=models.Index(fields=['site'], name='db_url_data_site_bb5907_idx'),
        ),
    ]
