# To execute this docker-compose yml file use `docker-compose -f docker-compose-v3-dynamic-grid.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker-compose -f docker-compose-v3-dynamic-grid.yml down`
version: "3"
services:
  node-docker2:
    image: selenium/node-docker:4.0.0-beta-3-20210426
    volumes:
      - ./assets:/opt/selenium/assets
      - ./NodeDocker/config.toml:/opt/bin/config.toml
    depends_on:
      - selenium-hub2
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub2
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  
  selenium-hub2:
    image: selenium/hub:4.0.0-beta-3-20210426
    container_name: selenium-hub2
    ports:
      - "4542:4442"
      - "4543:4443"
      - "4544:4444"
